### ISSUE TITLE
Quick Questions for the readme.md

### ISSUE THREAD

**Issue by hippyau** [tostc/CVFS#1]
Hi there!

a) Does support nested directories, ie:  /tmp/tmpdir/file.txt   ?  

       Seems not, but possible to implement?  Like nest a VFS in a file, inside a directory?

b) Does support binary files  ?

       How to get size?

Cheers, 
  Hippy

**Comment by tostc** [comment]
Hello Hippy,

thank you for using this library :D

a) There is support for nested directories. The path depth is theoretically unlimited, in practice it is limited by the amount of RAM in your PC and the maximum length of a string. 

b) You can write any type of file, whether it is a binary file or a text file. To find out the size of a file, you can either call `CVFS::FileSize(VFSNode)` or with `CVFSFileStream::Size()` when you have the file open. 

If you have any further questions, don't hesitate and ask. 

Cheers,
tostc

**Comment by hippyau** [comment]
Thanks, it seems like it is really cool!  I was making a rookie mistake...

I was trying a quick hack of demo, and getting a segfault on a file not exists,  but realized I was not catching exceptions.  Exists a way to just return true/false easily, or do I have to write wrapper? 

Cheers :)

**Comment by tostc** [comment]
No each method can throw a `CVFSException`.

**Comment by hippyau** [comment]
Yer, i'm an idiot,  I think I have worked out now :)
